[images]
  remote_images = ["https://source.unsplash.com/.*", "https://images.unsplash.com/.*", "https://ext.same-assets.com/.*", "https://ugc.same-assets.com/.*"]

[build]
  command = "bun run build"
  publish = "out"

# Static site rules for SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
EOF  
cd /home/project && cd seo-link-site && cat > netlify.toml << 'EOF'
[images]
  remote_images = ["https://source.unsplash.com/.*", "https://images.unsplash.com/.*", "https://ext.same-assets.com/.*", "https://ugc.same-assets.com/.*"]

[build]
  command = "bun run build"
  publish = "out"

# Static site rules for SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
